### ISSUE TITLE
Evaluation - Determine evaluation functions / methods

### ISSUE THREAD

**Issue by nnistelrooij** [nnistelrooij/Information-Retrieval#3]
Determine the functions or methods that we will be using for the evaluation. Think of the effect of caching, getting the average wall-clock time of 10 runs or comparing BM25 and Term Proximity speeds with null hypothesis significance testing.

**Comment by rusane** [comment]
## Evaluation
Assuming that we are only going to re-rank the top *k* documents using term proximity:
- We can cache* the top *k* results from BM25 before re-ranking (maybe test effects of caching vs no caching)
- We could compare the ranked lists (with or without term proximity) using Kendall's tau to measure their similarity
- We can evaluate the ranked lists with Average Precision (one query) or MAP (multiple queries) to validate whether the top *k* documents are indeed ranked better than without term proximity
- NDCG would be possible if the relevance judgements are graded (but not sure if they are in Robust04)

*Caching is possible with the module `cachetools`, which is a wrapper.

## Run time performance
Timing could be achieved with the built-in `timeit` module. 

**Example:**
```python
# The code to set up the database should be defined before timing, 
# i.e., `db` should be defined. 
# The actual querying of the database should be implemented 
# in the placeholder function `search(db)` to time it.
from timeit import Timer

def search(db):
    """
    Query the database.
    """

my_timer = Timer(stmt='search(db)', globals=globals())
nr_of_executions = 100
total_time = my_timer.timeit(number=nr_of_executions)
mean_time = total_time / nr_of_executions
print(...)
```
